POST {{host}}/contains
Content-Type: application/json
Accept: application/json

{
  "polygon": [
    {
      "lat": 10,
      "lng": 10
    },
    {
      "lat": 20,
      "lng": 20
    },
    {
      "lat": 30,
      "lng": 10
    }
  ],
  "point": {
    "lat": 15,
    "lng": 15
  }
}